language: node_js
node_js:
  - '1.3.10'

before_script:
  - 'npm install -g bower grunt-cli'

after_success:
 - 'curl -l http://somewherebetween.us:8080/update_server.php'

deploy:
- provider: heroku
  api_key: 'd2757858-57df-4036-9980-a5143ca522f1'
