#!/bin/bash

echo ""
echo "--------------------------------"
echo "create meeting"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/create?nickname=rob&guestID=1234&meetingID=4434"
echo ""
echo "--------------------------------"
echo "add user"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/addguest?nickname=rob&guestID=1234&meetingID=4434&latitude=30.5&longitude=-97.6"
echo ""
echo "--------------------------------"
echo "list users"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/getguests?meetingID=4434"
echo ""
echo "--------------------------------"
echo "remove user"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/removeguest?nickname=rob&guestID=1234&meetingID=4434"
echo ""
echo "--------------------------------"
echo "list users"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/getguests?meetingID=4434"
echo ""
echo "--------------------------------"
echo "add users"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/addguest?nickname=rob1&guestID=1234&meetingID=4434&latitude=30.5&longitude=-97.6"
curl -l "http://localhost:1337/Meeting/addguest?nickname=rob2&guestID=1235&meetingID=4434&latitude=32.5&longitude=-96.6"
curl -l "http://localhost:1337/Meeting/addguest?nickname=rob3&guestID=1236&meetingID=4434&latitude=34.5&longitude=-94.6"
echo ""
echo "--------------------------------"
echo "get meeting center"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/getcenter?meetingID=4434"
echo ""
echo "--------------------------------"
echo "remove users"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/removeguest?nickname=rob1&guestID=1234&meetingID=4434"
curl -l "http://localhost:1337/Meeting/removeguest?nickname=rob2&guestID=1235&meetingID=4434"
curl -l "http://localhost:1337/Meeting/removeguest?nickname=rob3&guestID=1236&meetingID=4434"
echo ""
echo "--------------------------------"
echo "list users"
echo "--------------------------------"
curl -l "http://localhost:1337/Meeting/getguests?meetingID=4434"
echo ""
echo "--------------------------------"
echo "test yelp service - find coffee"
echo "--------------------------------"
curl -l "http://localhost:1337/Yelp/testYelpService?venueType=coffee&latitude=30.3&longitude=-97.7"
echo ""
echo "--------------------------------"
echo "test yelp service - find mexican"
echo "--------------------------------"
curl -l "http://localhost:1337/Yelp/testYelpService?venueType=mexican&latitude=30.3&longitude=-97.7"
echo ""
echo "--------------------------------"
echo "test google address-geolocation service"
echo "--------------------------------"
curl -l "http://localhost:1337/GoogleMaps/getGeoLocationFromAddress?address=121%20Richard%20Road,%20Georgetown,%20Tx%2078626"
echo ""
