#!/bin/bash

echo ""
echo "--------------------------------"
echo "add venue"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/addvenue?venueID=4494&businessname=ABC%20Moving&meetingID=4434&latitude=30.5&longitude=-97.6"
echo ""
echo "--------------------------------"
echo "add voter"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/addvoter?venueID=12345&meetingID=4434&voterID=rob"
echo ""
echo "--------------------------------"
echo "show voters"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/showvotes?meetingID=4434"
echo ""
echo "add voter"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/addvoter?venueID=12345&meetingID=4434&voterID=ralph"
echo ""
echo "--------------------------------"
echo "show voters"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/showvotes?meetingID=4434"
echo ""
echo "--------------------------------"
echo "remove voter"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/removevoter?venueID=12345&meetingID=4434&voterID=rob"
echo ""
echo "--------------------------------"
echo "show voters"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/showvotes?meetingID=4434"
echo ""
echo "--------------------------------"
echo "remove venue"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/removevenue?venueID=12345&meetingID=4434"
