#!/bin/bash

echo ""
echo "--------------------------------"
echo "add venue"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/addvenue?venueid=4494&businessname=ABC%20Moving&meetingid=4434&latitude=30.5&longitude=-97.6"
echo ""
echo "--------------------------------"
echo "add voter"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/addvoter?venueid=12345&meetingid=4434&voterid=rob"
echo ""
echo "--------------------------------"
echo "show voters"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/showvotes?meetingid=4434"
echo ""
echo "add voter"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/addvoter?venueid=12345&meetingid=4434&voterid=ralph"
echo ""
echo "--------------------------------"
echo "show voters"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/showvotes?meetingid=4434"
echo ""
echo "--------------------------------"
echo "remove voter"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/removevoter?venueid=12345&meetingid=4434&voterid=rob"
echo ""
echo "--------------------------------"
echo "show voters"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/showvotes?meetingid=4434"
echo ""
echo "--------------------------------"
echo "remove venue"
echo "--------------------------------"
curl -l "http://localhost:1337/Venue/removevenue?venueid=12345&meetingid=4434"
